/**
* Smart Commuter Parking (SPP)
* Provides access to Västtrafik commuter parking API
*
* OpenAPI spec version: 3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package se.larsson.parking.network.models

/**
 * 
 * @param Name 
 * @param StopArea 
 * @param DepartureTime 
 * @param Type 
 * @param ShortName 
 * @param DepartsInMinutes Minutes until departure
 * @param ArrivalTime 
 * @param Destination 
 */
data class Departure (
    val Name: kotlin.String,
    val StopArea: StopArea,
    val DepartureTime: java.time.LocalDateTime,
    val ShortName: kotlin.String,
    /* Minutes until departure */
    val DepartsInMinutes: kotlin.Int,
    val ArrivalTime: java.time.LocalDateTime,
    val Type: kotlin.String? = null,
    val Destination: Destination? = null
)

