/**
* Smart Commuter Parking (SPP)
* Provides access to Västtrafik commuter parking API
*
* OpenAPI spec version: 3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package se.larsson.parking.network.models

/**
 * 
 * @param Departures Departures from the parking area, sorted by minutes until departure
 * @param Name 
 * @param StopAreas 
 * @param Id 
 * @param ParkingLots 
 */
data class ParkingArea (
    val Name: kotlin.String,
    val StopAreas: kotlin.Array<StopArea>,
    val Id: kotlin.Long,
    val ParkingLots: kotlin.Array<ParkingLot>,
    /* Departures from the parking area, sorted by minutes until departure */
    val Departures: kotlin.Array<Departure>? = null
)
