/**
* Smart Commuter Parking (SPP)
* Provides access to Västtrafik commuter parking API
*
* OpenAPI spec version: 3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package se.larsson.parking.network.models


/**
 * 
 * @param Name The parking lot type
 * @param Number 
 */
data class ParkingType (
    /* The parking lot type */
    val name: String,
    val Number: kotlin.Int
) {

    /**
    * The parking lot type
    * Values: cARPARK,sMARTCARPARK
    */
    enum class Name(val value: String){
         CARPARK("CARPARK"),
         SMARTCARPARK("SMARTCARPARK")
    }

}

