/**
* Smart Commuter Parking (SPP)
* Provides access to Västtrafik commuter parking API
*
* OpenAPI spec version: 3.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package se.larsson.parking.network.models


/**
 * 
 * @param Name 
 * @param Municipality 
 * @param Gid 
 */
data class StopArea (
    val Name: kotlin.String,
    val Municipality: kotlin.String,
    val Gid: kotlin.Long
) {

}

